title: "NightB1adeâ€™s Board Game Helper"
titles_from_headings:
    enabled: false
defaults:
    -
        values:
            layout: default
    -
        scope:
            path: AstroKnights
        values:
            gametitle: Astro Knights
